In [1]:
import pandas as pd
import numpy as np

In [16]:
DF=pd.read_csv('train.csv')
atts=pd.read_csv('attributes.csv')

In [17]:
for i in range(0, len(atts)):
    if atts.iloc[i]['Type']=='Categorical':
        col_name=atts.iloc[i]['Attribute']
        DF=pd.get_dummies(DF, columns=[col_name])

In [21]:
DF[:5]

,Id,LotFrontage,LotArea,LotShape,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,...,MiscVal_15500,SaleType_COD,SaleType_CWD,SaleType_Con,SaleType_ConLD,SaleType_ConLI,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD
0,1,65.0,8450,Reg,2003,2003,196.0,706,0,150,...,0,0,0,0,0,0,0,0,0,1
1,2,80.0,9600,Reg,1976,1976,0.0,978,0,284,...,0,0,0,0,0,0,0,0,0,1
2,3,68.0,11250,IR1,2001,2002,162.0,486,0,434,...,0,0,0,0,0,0,0,0,0,1
3,4,60.0,9550,IR1,1915,1970,0.0,216,0,540,...,0,0,0,0,0,0,0,0,0,1
4,5,84.0,14260,IR1,2000,2000,350.0,655,0,490,...,0,0,0,0,0,0,0,0,0,1